### ISSUE TITLE
Deleted Text

### ISSUE THREAD

**Issue by EpicGamer200245** [NKHook/NKHook5#12]
**Describe the bug**
NKHook seems to delete the text in game for some things, such as the name of super storm in agents shop or everything related to the wizard or boomerang monkey. Like with the super storm in the shop it has no name or the wizard monkey not having a name, description, upgrade name, or upgrade description.

**To Reproduce**
1. Use NKHook
2. Look at the name of super storm in agents shop or wizard and boomerang in towers building.

**Expected behavior**
It actually has text.

**Screenshots**
![image](https://user-images.githubusercontent.com/56707910/200203749-8cbcd726-0b55-4b34-a1b8-78870b8d3da5.png)
![image](https://user-images.githubusercontent.com/56707910/200203781-f00dcff2-4dce-4cf3-b741-a8c0208d14d5.png)
![image](https://user-images.githubusercontent.com/56707910/200203810-fe138434-efab-4cf6-9f1d-4d6b9ef1b0a9.png)

**Additional context**
I tried this without using mods as well. And it shows the text when I remove NKHook from BTD5.

**Comment by DisabledMallis** [comment]
This is a result of injected/custom tower ids. Not exactly sure why, so its gonna take some time to figure out.

**Comment by DisabledMallis** [comment]
Should be fixed in new update
