### ISSUE TITLE
Repo doesn't tell you how to use NKHook5 at all, intead focusing on syntax

### ISSUE THREAD

**Issue by qwertyuiop265000** [NKHook/NKHook5#13]
Problem: The repo's readme doesn't even hint at how any of this works.

The solution: get a better repo description. 

There is no alternative method.

**Comment by EpicGamer200245** [comment]
To install NKHook, there are instructions to use it on the first release of NKHook, which says:

How to install:

1. Download wininet.dll (This is the bootstrapper)
2. Download NKHook5.dll (This is the mod loader)
3. Copy wininet.dll into your game's folder
4. Copy NKHook5.dll into your game's folder
5. Create a "Mods" folder in your game's folder

**Comment by qwertyuiop265000** [comment]
but how does one install a mod, where it's a .zip

BTD Evolution, for instance.

**Comment by EpicGamer200245** [comment]
BTD Evolution hasn't come out yet, you are able to compile the mod yourself with the DevKit but the mod hasn't been released yet meaning that it still could give an error or be buggy. The mods that have been released are the ones in the #downloads channel on the discord.

**Comment by EpicGamer200245** [comment]
The ones that have been released you just put the .nkh file in the Mods folder.

**Comment by qwertyuiop265000** [comment]
There is exactly ONE "released" mod, and it's very much WIP.

**Comment by EpicGamer200245** [comment]
Yeah. Not many people have made mods for it, it just being that mod and the other WIP BTD Evolution mod.

**Comment by qwertyuiop265000** [comment]
Then i would like to learn how to make NKHook5 mods.

**Comment by EpicGamer200245** [comment]
> Then i would like to learn how to make NKHook5 mods.

This is more from the original release: to create a mod:

Setting up DevKit.exe for mod development:

1. Create a new folder, in which you will have all of your mod projects
2. Copy DevKit.exe into the folder
3. Open command prompt in the folder
4. Run DevKit.exe -h to view the help menu
5. Run DevKit.exe -s and follow the instructions
6. Run DevKit.exe -c <mod_name> to create a new mod project with the name <mod_name> NOTE: mod names MUST BE alphanumeric (a-z, A-Z, and 0-9)
7. Run DevKit.exe -p <mod_name> to package a mod with the name <mod_name> for distribution.

**Comment by DisabledMallis** [comment]
I don't even follow my own code standards anymore :trollface: so I replaced that section with install instructions.
