### ISSUE TITLE
Possible other "BTD5" engine support?

### ISSUE THREAD

**Issue by Icephoenix2019** [NKHook/NKHook5#14]
**Is your feature request related to a problem? Please describe.**
No, it is more of a request

**Describe the solution you'd like**
A mod loader for NKHook5, ether that or NKHookC for BMC
The engines I _assume_ are the same except with some minor differences
I wouldn't say this is needed right now, more of a want than a need.

**Describe alternatives you've considered**
I have not really considered alternatives but I thought it would be nice for BMC modders

**Additional context**
I unfortunately have no additional context

**Comment by DisabledMallis** [comment]
It is true that BMC and BTD5 both use NewFramework, however they are different version of NewFramework. It wouldn't be extremely difficult to make a version for BMC, but it just isn't one of my goals at the moment.

**Comment by Icephoenix2019** [comment]
Totally fine, like I said, more of a want than a need 👍
