### ISSUE TITLE
Game termination detected error

### ISSUE THREAD

**Issue by Twingamerdudes** [NKHook/NKHook5#16]
**Describe the bug**
After making a mod (in this case I got btd evolution to make sure everything was working) and trying to run it using -r, the console outputs: Game termination detected, exiting... Steam also shows the allow this game to run popup, so I am assuming that might be causing it not to run. However, I don't know how to get rid of it or know any other way around it.

**To Reproduce**
1. Setup a mod or just use btd-evolution
2. Run the command in powershell ./DevKit.exe -r "(name of mod)"

**Expected behavior**
The game should boot up with the mod installed and working.

**Screenshots**
![image](https://user-images.githubusercontent.com/81382687/212566990-7f0f4709-a74b-44aa-b32d-87e8f4c19e41.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 0.6.0

**Additional context**
Probably just me being an idiot again.

**Comment by Twingamerdudes** [comment]
I just compiled the mod manually and then dragged it into the mods folder

**Comment by DisabledMallis** [comment]
Yea the run feature doesn't work at the moment, probably just gonna remove it in the near future anyway.
