### ISSUE TITLE
Failed to Find Signatures and Apply Patches

### ISSUE THREAD

**Issue by EpicGamer200245** [NKHook/NKHook5#20]
**Describe the bug**
Failed to find the signatures: "CProjectile_Clone", "CTowerFactory_GetTowerName", "CWeaponFactory_CCTOR", "JsonObject_ReadBoolProperty", and "JsonObject_ReadIntProperty". Also when it tries to apply patches it fails the apply the patches: "CProjectile::Clone", "CTowerFactory::GetTowerName", and "CWeaponFactory::Constructor". 

**Screenshots**
![image](https://user-images.githubusercontent.com/56707910/235381988-7833efb7-9bc2-4ef7-a39f-561ce38bc6cd.png)

![image](https://user-images.githubusercontent.com/56707910/235382104-95476cb7-90d1-408a-9f32-c2eb0ef2028a.png)

**Comment by DisabledMallis** [comment]
Fixed
