### ISSUE TITLE
Texture Pixel Offset

### ISSUE THREAD

**Issue by EpicGamer200245** [NKHook/NKHook5#21]
With textures currently there is an issue which creates a 2 pixel gap between each texture:

![image](https://github.com/NKHook/NKHook5/assets/56707910/773cbf9e-2655-4889-b82c-05d18d998ea2)

The pixel gap between each texture can be fixed by reducing the numbers for "w", "h", "aw", and "ah" in the spreadsheet files by 1, after doing that I get this result with the  tower in the image before:

![image](https://github.com/NKHook/NKHook5/assets/56707910/841d9b7c-e42f-4036-a93e-6a1a6694c737)

**Comment by DisabledMallis** [comment]
I did not know this was the cause lol, I'll fix it asap!
