### ISSUE TITLE
Devkit saying incorrect path when the path is correct (Copied from .exe file)

### ISSUE THREAD

**Issue by NotAlixx** [NKHook/NKHook5#23]
Here's the image! Please Help!
![Zrzut ekranu 2023-08-28 175155](https://github.com/NKHook/NKHook5/assets/143433930/06d930c2-604f-4bc1-9380-dbc685d629ae)

**Comment by DisabledMallis** [comment]
Did you accidently include quotes in the path?

**Comment by DisabledMallis** [comment]
Inactive, closing
