### ISSUE TITLE
Suggestion: Multiplier

### ISSUE THREAD

**Issue by EpicGamer200245** [NKHook/NKHook5#4]
Make it so that if you have a line like:

gameData.setHealth(gameData.getHealth()-1)

Instead of copy and pasting that in your code 5 times to can do:

gameData.setHealth(gameData.getHealth()-1 multiplier.x5)

So you put:

 multiplier.x<how many times you want to multiply) 

At the end of the parentheses, you put a space and put that. The reason why I want this is that you don't have code like this:

gameData.setHealth(gameData.getHealth()-1)
gameData.setHealth(gameData.getHealth()-1)
gameData.setHealth(gameData.getHealth()-1)
gameData.setHealth(gameData.getHealth()-1)
gameData.setHealth(gameData.getHealth()-1)

Instead like this:

gameData.setHealth(gameData.getHealth()-1 multiplier.x5)

**Comment by DisabledMallis** [comment]
gameData.setHealth(gameData.getHealth()-(1*5))

?
this is just math lol
